language: php
services: mysql
php:
  - "5.4"
  - "5.3"
env:
  - DB=mysql
before_script:
  - composer install
  - mysql -e 'create database coretest;'

script: 
- phpunit tests/CSVTest.php
- phpunit tests/JSONTest.php